// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWtwUwfm-s6wsvXdEohJ4DpomRQEjMg54',
    appId: '1:1039915780058:web:63c3c0ee3a4af585fde2e3',
    messagingSenderId: '1039915780058',
    projectId: 'deckshare-2073f',
    authDomain: 'deckshare-2073f.firebaseapp.com',
    storageBucket: 'deckshare-2073f.firebasestorage.app',
    measurementId: 'G-K3Z33T9YWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvNzuZUafysbg675dyBcojhewA5s7O4SE',
    appId: '1:1039915780058:android:1f8f1391bffc77bdfde2e3',
    messagingSenderId: '1039915780058',
    projectId: 'deckshare-2073f',
    storageBucket: 'deckshare-2073f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK7osxzYRaxvZIeCqu8DaG68plPsyq2cU',
    appId: '1:1039915780058:ios:6b38253d796da81efde2e3',
    messagingSenderId: '1039915780058',
    projectId: 'deckshare-2073f',
    storageBucket: 'deckshare-2073f.firebasestorage.app',
    iosBundleId: 'com.example.deckShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK7osxzYRaxvZIeCqu8DaG68plPsyq2cU',
    appId: '1:1039915780058:ios:6b38253d796da81efde2e3',
    messagingSenderId: '1039915780058',
    projectId: 'deckshare-2073f',
    storageBucket: 'deckshare-2073f.firebasestorage.app',
    iosBundleId: 'com.example.deckShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWtwUwfm-s6wsvXdEohJ4DpomRQEjMg54',
    appId: '1:1039915780058:web:4c8dd85fb3b6116afde2e3',
    messagingSenderId: '1039915780058',
    projectId: 'deckshare-2073f',
    authDomain: 'deckshare-2073f.firebaseapp.com',
    storageBucket: 'deckshare-2073f.firebasestorage.app',
    measurementId: 'G-P36WY4BYZ0',
  );

}